# For this project, we use ReadTheDocs only for Pull Request previews. GitHub
# pages currently hosts the actual website.
version: 2


build:
  os: "ubuntu-lts-latest"
  tools:
    nodejs: "24"

  commands:
    # Should be immutable, but the lockfile is way out of date.
    # TODO: Change back to immutable after merging <https://github.com/satcamp/SatCamp-website/pull/14>
    - "corepack yarn install --no-immutable"
    - "corepack yarn build"

    - "mkdir --parents $READTHEDOCS_OUTPUT/html/"
    - "mv dist/* $READTHEDOCS_OUTPUT/html/."
