# Builds the site on pull requests to verify it compiles (no deploy)
name: Build website

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Enable corepack
        run: corepack enable
      - name: Set up Node
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: "yarn"
      - name: Install dependencies
        # TODO: Remove --no-immutable after <https://github.com/satcamp/SatCamp-website/pull/14> is merged
        run: yarn install --no-immutable
      - name: Build
        run: yarn build
